// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "apiBase": string;
      "apiKey": string;
      "model": string;
      "modelProviderGroups": string;
      "modelProviderGroupsMigrationVersion": number;
      "lastUsedModelEntryId": string;
      "systemPrompt": string;
      "showPopupAddText": boolean;
      "semanticScholarApiKey": string;
      "temperaturePrimary": string;
      "maxTokensPrimary": string;
      "temperatureSecondary": string;
      "maxTokensSecondary": string;
      "temperatureTertiary": string;
      "maxTokensTertiary": string;
      "temperatureQuaternary": string;
      "maxTokensQuaternary": string;
      "enableAgentMode": boolean;
      "obsidianVaultPath": string;
      "obsidianTargetFolder": string;
      "obsidianAttachmentsFolder": string;
      "obsidianNoteTemplate": string;
      "locale": string;
      "mineruAutoWatchCollections": string;
      "mineruGlobalAutoParse": boolean;
      "mineruExcludePatterns": string;
    };
  }
}
