// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "apiBase": string;
      "apiKey": string;
      "model": string;
      "modelProviderGroups": string;
      "modelProviderGroupsMigrationVersion": number;
      "lastUsedModelEntryId": string;
      "systemPrompt": string;
      "showPopupAddText": boolean;
      "semanticScholarApiKey": string;
      "temperaturePrimary": string;
      "maxTokensPrimary": string;
      "temperatureSecondary": string;
      "maxTokensSecondary": string;
      "temperatureTertiary": string;
      "maxTokensTertiary": string;
      "temperatureQuaternary": string;
      "maxTokensQuaternary": string;
      "enableAgentMode": boolean;
      "enableClaudeCodeMode": boolean;
      "agentBackendBridgeUrl": string;
      "agentClaudeConfigSource": string;
      "agentPermissionMode": string;
      "conversationSystem": string;
      "enableCodexAppServerMode": boolean;
      "codexAppServerModel": string;
      "codexAppServerReasoning": string;
      "codexAppServerPath": string;
      "codexAppServerConversationModeMap": string;
      "codexAppServerZoteroMcpToolsEnabled": boolean;
      "codexNativeSkillRoutingMode": string;
      "codexAppServerGlobalConversationMap": string;
      "codexAppServerPaperConversationMap": string;
      "codexAppServerLastAllocatedConversationKeyMap": string;
      "codexAppServerLastAllocatedGlobalConversationKey": number;
      "codexAppServerLastAllocatedPaperConversationKey": number;
      "claudeCodeConversationModeMap": string;
      "claudeCodeGlobalConversationMap": string;
      "claudeCodePaperConversationMap": string;
      "claudeCodeLastAllocatedConversationKeyMap": string;
      "claudeCodeLastAllocatedGlobalConversationKey": number;
      "claudeCodeLastAllocatedPaperConversationKey": number;
      "claudeCodeModel": string;
      "claudeCodeReasoning": string;
      "claudeCodeBlockStreaming": boolean;
      "claudeCodeAutoCompact": boolean;
      "claudeCodeAutoCompactThreshold": number;
      "obsidianVaultPath": string;
      "obsidianTargetFolder": string;
      "obsidianAttachmentsFolder": string;
      "obsidianNoteTemplate": string;
      "notesDirectoryNickname": string;
      "locale": string;
      "mineruAutoWatchCollections": string;
      "mineruGlobalAutoParse": boolean;
      "mineruSyncEnabled": boolean;
      "mineruExcludePatterns": string;
    };
  }
}
